package com.epam.nb.bean;

public enum RequestParam {

	NEW_NOTEBOOK_REQUEST,
	NEW_NOTE_REQUEST,
	EXIST_NOTE_REQUEST,
	CHANGED_NOTE_REQUEST,
	FIND_NOTE_BY_DATE_REQUEST,
	FIND_ALL_NOTES_REQUEST,
	NOTE_TITLE_REQUEST,
	NOTE_AUTHOR_REQUEST

}
